<?php
/**
 * Created by PhpStorm.
 * Filename:  Student.php
 * User:      cmder
 * Date:      2018/1/21
 * Time:      17:28
 */
namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //指定表名
    protected $table= 'student';

    //指定id
    protected $primaryKey= 'id';

    //指定允许批量复制的字段
    protected $fillable = ['name', 'age'];

    //指定不允许批量复制的字段
    protected $guarded = [];

    //自动维护时间戳
    public $timestamps = true;

    protected function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }
}